# Generated by Django 5.2.12 on 2026-04-05 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("source_file", models.CharField(max_length=255)),
                ("total", models.IntegerField(default=0)),
                ("processed", models.IntegerField(default=0)),
                ("failed", models.IntegerField(default=0)),
                ("paused", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("running", "В работе"),
                            ("done", "Завершён"),
                            ("failed", "Ошибка"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("webhook_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluation_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Батч-задание",
                "verbose_name_plural": "Батч-задания",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("file_path", models.TextField(blank=True, null=True)),
                ("file_url", models.TextField()),
                (
                    "city",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "trainer",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("group_name", models.CharField(blank=True, max_length=255, null=True)),
                ("file_name", models.CharField(blank=True, max_length=255, null=True)),
                ("teacher_name", models.TextField(blank=True, null=True)),
                ("topic", models.TextField(blank=True, null=True)),
                ("scores", models.JSONField(blank=True, null=True)),
                ("total_score", models.FloatField(blank=True, null=True)),
                ("score_percentage", models.FloatField(blank=True, null=True)),
                (
                    "score_level",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("feedback", models.TextField(blank=True, null=True)),
                ("llm_result", models.JSONField(blank=True, null=True)),
                ("report_path", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("processing", "Обрабатывается"),
                            ("done", "Готово"),
                            ("failed", "Ошибка"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("current_step", models.IntegerField(default=0)),
                ("error", models.TextField(blank=True, null=True)),
                (
                    "extraction_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("doc_lang", models.CharField(blank=True, max_length=10, null=True)),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("doc_chars", models.IntegerField(blank=True, null=True)),
                ("prompt_tokens", models.IntegerField(default=0)),
                ("completion_tokens", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="batch.evaluationjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оценка",
                "verbose_name_plural": "Оценки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="evaluationjob",
            index=models.Index(fields=["status"], name="batch_evalu_status_ee7bcb_idx"),
        ),
        migrations.AddIndex(
            model_name="evaluationjob",
            index=models.Index(
                fields=["-created_at"], name="batch_evalu_created_7b27d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evaluation",
            index=models.Index(
                fields=["job", "status"], name="batch_evalu_job_id_569c93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evaluation",
            index=models.Index(
                fields=["-created_at"], name="batch_evalu_created_67a0a2_idx"
            ),
        ),
    ]
