# Generated by Django 5.2.12 on 2026-04-10 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("batch", "0001_initial"),
        ("evaluators", "0001_stage2_multiconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluation",
            name="evaluator_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evaluations",
                to="evaluators.evaluatorconfig",
            ),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="used_fix_docx",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="used_vision_ocr",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="was_empty_doc",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="evaluationjob",
            name="evaluator_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evaluation_jobs",
                to="evaluators.evaluatorconfig",
            ),
        ),
    ]
