# Generated by Django 5.2.12 on 2026-04-10 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "body",
                    models.TextField(
                        help_text="Плейсхолдеры: {rubric}, {student_work}"
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Шаблон промпта",
                "verbose_name_plural": "Шаблоны промптов",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Rubric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("version", models.CharField(default="v1", max_length=20)),
                ("file_ru", models.FileField(blank=True, upload_to="rubrics/")),
                ("file_kk", models.FileField(blank=True, upload_to="rubrics/")),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Рубрика",
                "verbose_name_plural": "Рубрики",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max_evaluation_slots", models.PositiveIntegerField(default=8)),
                ("max_llm_calls", models.PositiveIntegerField(default=50)),
                ("max_downloads", models.PositiveIntegerField(default=100)),
                ("max_concurrent_vision", models.PositiveIntegerField(default=3)),
            ],
            options={
                "verbose_name": "Системные настройки",
                "verbose_name_plural": "Системные настройки",
            },
        ),
        migrations.CreateModel(
            name="EvaluatorConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "llm_model",
                    models.CharField(
                        choices=[
                            ("openai/gpt-oss-120b", "gpt-oss-120b (основная)"),
                            ("deepseek-ai/DeepSeek-V3.2", "DeepSeek-V3.2 (рус/каз)"),
                            ("moonshotai/Kimi-K2.5", "Kimi-K2.5 (резерв #1)"),
                            (
                                "meta-llama/Llama-4-Maverick-17B-128E-Instruct",
                                "Llama-4-Maverick (резерв #2)",
                            ),
                            ("astanahub/alemllm", "AlemLLM (казахстанская)"),
                        ],
                        default="openai/gpt-oss-120b",
                        max_length=120,
                    ),
                ),
                (
                    "vision_model",
                    models.CharField(
                        choices=[
                            (
                                "Qwen/Qwen3-VL-235B-A22B-Instruct",
                                "Qwen3-VL (рекомендуется)",
                            ),
                            ("none", "Отключить Vision OCR"),
                        ],
                        default="Qwen/Qwen3-VL-235B-A22B-Instruct",
                        max_length=120,
                    ),
                ),
                (
                    "whisper_model",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "openai/whisper-large-v3-turbo",
                                "Whisper turbo (быстрый)",
                            ),
                            ("openai/whisper-large-v3", "Whisper large-v3"),
                            ("none", "Отключить"),
                        ],
                        default="none",
                        max_length=80,
                    ),
                ),
                ("temperature", models.FloatField(default=0.1)),
                ("max_tokens", models.PositiveIntegerField(default=4096)),
                ("evaluation_slots", models.PositiveIntegerField(default=1)),
                (
                    "language_mode",
                    models.CharField(
                        choices=[
                            ("auto", "Определять автоматически (langdetect)"),
                            ("ru", "Всегда русский"),
                            ("kk", "Всегда казахский"),
                        ],
                        default="auto",
                        max_length=10,
                    ),
                ),
                ("enable_doc_fix", models.BooleanField(default=True)),
                ("enable_google_docs", models.BooleanField(default=True)),
                ("enable_python_docx", models.BooleanField(default=True)),
                ("enable_pymupdf_fallback", models.BooleanField(default=True)),
                ("enable_vision_ocr", models.BooleanField(default=True)),
                ("enable_audio", models.BooleanField(default=False)),
                ("enable_validation", models.BooleanField(default=True)),
                ("min_text_chars", models.PositiveIntegerField(default=50)),
                ("vision_max_pages", models.PositiveIntegerField(default=10)),
                ("vision_dpi", models.PositiveIntegerField(default=150)),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[
                            ("beles", "Beles API"),
                            ("webhook", "Webhook (POST)"),
                            ("db_only", "Только БД"),
                        ],
                        default="db_only",
                        max_length=20,
                    ),
                ),
                ("beles_base_url", models.URLField(blank=True)),
                ("beles_api_key", models.CharField(blank=True, max_length=512)),
                (
                    "beles_endpoint_tpl",
                    models.CharField(
                        blank=True,
                        default="/postcourse/materials/{id}/ai-analysis/",
                        max_length=500,
                    ),
                ),
                ("beles_http_method", models.CharField(default="PATCH", max_length=10)),
                ("webhook_url", models.URLField(blank=True)),
                ("enable_retry", models.BooleanField(default=True)),
                ("retry_attempts", models.PositiveIntegerField(default=5)),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        help_text="X-API-Key для /api/ev/<slug>/…",
                        max_length=255,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluator_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prompt_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluator_configs",
                        to="evaluators.prompttemplate",
                    ),
                ),
                (
                    "rubric",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluator_configs",
                        to="evaluators.rubric",
                    ),
                ),
            ],
            options={
                "verbose_name": "Конфигурация оценщика",
                "verbose_name_plural": "Конфигурации оценщиков",
                "ordering": ["slug"],
            },
        ),
    ]
